apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "mysql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  # echo -n 'rootpass123' | base64
  MYSQL_ROOT_PASSWORD: {{ .Values.rootPassword | default "cm9vdHBhc3MxMjM=" }}
