apiVersion: v1
kind: Service
metadata:
  name: {{ include "webserver.fullname" . }}
  labels:
    app: {{ include "webserver.name" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.service.nodePort | default 30080 }}
  selector:
    app: {{ include "webserver.name" . }}
