apiVersion: v2
name: parent-chart
description: internal K8s app stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mysql
    version: 0.1.0
    repository: "file://charts/mysql"
  - name: webserver
    version: 0.1.0
    repository: "file://charts/webserver"

