apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pod-watcher.fullname" . }}
  labels:
    app: pod-watcher
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pod-watcher
  template:
    metadata:
      labels:
        app: pod-watcher
    spec:
      serviceAccountName: pod-watcher-sa
      containers:
        - name: pod-watcher
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              value: {{ .Values.namespace }}
