apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-watcher-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-watcher-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-watcher-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-watcher-role
subjects:
  - kind: ServiceAccount
    name: pod-watcher-sa
